spring:
  application:
    name: leaguetracker
  profiles:
    active: dev # Default profile, can be overridden
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://prod-db:5432/prod_database
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        "[format_sql]": true
  data:
    redis:
      host: redis-prod
      port: 6379
      password: your-prod-password
      timeout: 2000
      connect-timeout: 2000
logging:
  level:
    "[org.springframework]": INFO
    root: INFO

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/leaguetracker
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        "[format_sql]": true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
      # No password for local development
      timeout: 2000
      connect-timeout: 2000
  # Enable cache debugging
  cache:
    type: redis
    redis:
      time-to-live: 86400000 # 24 hours in milliseconds
      cache-null-values: false

logging:
  level:
    root: INFO
    "[org.hibernate.SQL]": OFF
    "[org.hibernate.type.descriptor.sql.BasicBinder]": WARN
    # Redis and cache logging
    "[org.springframework.data.redis]": DEBUG
    "[org.springframework.cache]": TRACE
    "[io.lettuce.core]": DEBUG
    "[com.leaguetracker.app]": DEBUG
    "[org.springframework.boot.autoconfigure.cache]": DEBUG

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
  data:
    redis:
      host: localhost
      port: 6379
      # Using test containers for Redis in test environment
      timeout: 1000
logging:
  level:
    "[org.springframework]": INFO
    root: INFO
