name: Run Tests

on:
  pull_request:
    branches: ["main", "develop"]
  workflow_run:
    workflows: ["Build Application"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_database
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U user -d test_database"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          echo "SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/test_database" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_USERNAME=user" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_PASSWORD=password" >> $GITHUB_ENV

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run Tests
        run: |
          cd backend
          chmod +x ./gradlew
          ./gradlew test --no-daemon
